lamp:
  cache:
    type: REDIS
  redis:
    ip: 127.0.0.1
    port: 16379
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
    database: 0
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: lamp
    password: lamp
  druid:
    username: 'lamp_defaults'
    password: 'lamp_defaults'
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.26.3.67:1521:helowin
  database:
    dbType: ORACLE
    # 需要初始化的数据库前缀
    initDatabasePrefix:
      - lamp_base
    # SCHEMA模式专用 当前服务的租户库前缀
    tenantDatabasePrefix: lamp_base
    # SCHEMA模式专用
    owner: ''
    multiTenantType: SCHEMA
    # COLUMN模式专用 隔离租户的字段
    tenantIdColumn: tenant_code
    isSeata: false
    p6spy: true

spring:
  datasource:
    dynamic:
      druid:
        validation-query: SELECT 'x' FROM DUAL
        db-type: oracle
    # 从这里结束(dynamic)，中间的这段配置用于 lamp.database.multiTenantType == DATASOURCE 时
    druid:
      db-type: oracle
      validation-query: SELECT 'x' FROM DUAL
